import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { log } from 'console';
import { removeOlderTweet } from '../controller/utilities';
import { PeopleList, TweetItem } from '../types-interfaces/types';
import {
    // AppThunk, 
    RootState
} from './store';

const initialState: {
    tweetsList: TweetItem[],
    people: PeopleList[]
} = {
    tweetsList: [],
    people: []
};

export const tweetItemSlice = createSlice({
    name: 'tweetList',
    initialState: initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        saveTweet: (state, action: PayloadAction<TweetItem>) => {
            // action.payload.id = Date.now();
            action.payload.likedCount = action.payload.likedCount | 0;
            action.payload.isLiked = action.payload.isLiked || false;
            state.tweetsList.push(action.payload)
        },
        clearAllTweet: (state) => { state.tweetsList = [] },
        deleteSpecificTweet: (state, action: PayloadAction<TweetItem>) => {
            state.tweetsList = state.tweetsList.filter((tweet) =>
                tweet.id !== action.payload.id)
        },
        likeUpdate: (state, action: PayloadAction<number>) => {
            let index = state.tweetsList.findIndex(x => x.id === action.payload);
            // state.tweetsList = state.tweetsList.filter((tweet) =>
            //     tweet.id !== action.payload &&
            //         tweet.isLiked === true ?
            //         tweet.isLiked = false : tweet.isLiked = true)
            console.log(index);

            if (state.tweetsList[index])
                if (state.tweetsList[index].isLiked === true) {
                    state.tweetsList[index].isLiked = false
                    if (state.tweetsList[index].likedCount > 0) {
                        state.tweetsList[index].likedCount -= 1
                    }
                } else {
                    state.tweetsList[index].isLiked = true
                    state.tweetsList[index].likedCount += 1
                }
        },
        removeOldEvents: (state: any) => {
            const currentTime = new Date().getTime();
            state.tweetsList = state.tweetsList.filter((event: any) => currentTime - event.timestamp <= 30000); // 30 seconds
        },

    },
    // // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // // including actions generated by createAsyncThunk or in other slices.
    // extraReducers: (builder) => {
    //     builder
    //         .addCase(incrementAsync.pending, (state) => {
    //             state.status = 'loading';
    //         })
    //         .addCase(incrementAsync.fulfilled, (state, action) => {
    //             state.status = 'idle';
    //             state.value += action.payload;
    //         })
    //         .addCase(incrementAsync.rejected, (state) => {
    //             state.status = 'failed';
    //         });
    // },
});



export const { clearAllTweet,
    saveTweet,
    deleteSpecificTweet,
    likeUpdate,
    removeOldEvents,
} = tweetItemSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const tweetsList = (state: RootState) => state.twitter.tweetsList;
export const peopleList = (state: RootState) => state.twitter.people;


export default tweetItemSlice.reducer;